name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ✅ Step 1: Checkout the repository
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      # ✅ Step 2: Setup Node.js
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # ✅ Step 3: Install dependencies and build
      - name: 'Install dependencies and build'
        run: |
          npm install --legacy-peer-deps
          npm run build

      # ✅ Step 4: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Nest-backend'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
